enum TiposDocumentacion{
    RENTAS_DEUDOR = "CERTIFICADO DE RENTAS",
    RENTAS_CONYUGE = "CERTIFICADO DE RENTAS CONYUGE",
    FORMULARIO_N22 = "FORMULARIO 22",
    CARPETA_TRIBUTARIA_DEUDOR = "CARPETA TRIBUTARIA DEUDO",
    CARPETA_TRIBUTARIA_CONYUGE = "CARPETA TRIBUTARIA CONYUGE",
    CERTIFICADO_COTIZACIONES = "COTIZACIONES",
    LIBRETA_MATRIMONIO = "LIBRETA DE MATRIMONIO",
    DEC_JURADA_SIMPLE_DEUDOR = "DECLARACION JURADA SIMPLE DEUDOR",
    DEC_JURADA_SIMPLE_CONYUGE = "DECLARACION JURADA SIMPLE CONYUGE",
    FINIQUITO_DEUDOR = "FINIQUITO DEUDOR",
    FINIQUITO_CONYUGE = "FINIQUITO CONYUGE",
    CERT_NACIMIENTO = "CERTIFICADO DE NACIMIENTO",
    PAGARE_CONYUGE = "COPIA DE PAGARE CONYUGE"
}